name: Service / Domain Addition
description: Request a new service to be added or submit specific domains
title: '[ADD] '
labels: ['addition']
assignees:
  - nota9x
body:
  - type: markdown
    attributes:
      value: |
        # Service / Domain Addition Request
        
        Help us expand the blocklist by providing information about services or domains.
  
  - type: textarea
    id: domains
    attributes:
      label: 1. Specific Domain(s) (Optional)
      description: If you know the specific domains, list them here. If you only know the service name, leave this blank.
      placeholder: example.com, tracker.example.com
    validations:
      required: false
  
  - type: textarea
    id: service-name
    attributes:
      label: 2. Service Name (Required)
      description: Which service or company do you want to block?
      placeholder: e.g., "ClassLink", "Impero", "New unknown tracker"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: 3. Description & Reason
      description: What does this service do?
      placeholder: e.g., "Screen monitoring," "MDM," "Web Filter," "Trackers"
    validations:
      required: true
  
  - type: textarea
    id: links
    attributes:
      label: 4. Helpful Links / Context
      description: Please provide a link to the service's website or any documentation. This helps us find the domains to block if you didn't list them above.
      placeholder: https://example.com
    validations:
      required: false
  
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate.
          required: true
        - label: I understand that if I don't provide domains, it may take longer for the maintainers to research and add this service.
          required: true
